services:
  zabbix-proxy:
    container_name: zabbix-proxy
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      ZBX_HOSTNAME: {$PROXY_HOSTNAME}
      ZBX_SERVER_HOST: {$SERVER_IP}:10051
      ZBX_PROXYMODE: 0
    image: zabbix/zabbix-proxy-mysql:6.2.6-alpine
    ports:
      - "10051:10051"
  service_mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: zabbix_proxy
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - zabbix-proxy-db:/var/lib/mysql
    deploy:
          resources:
            limits:
              cpus: '1' # Limit CPU Usage to 1 Core (optional)
              memory: 800m # Limit Memory Usage to 800 Mib (optional)
    hostname: mysql
volumes:
  zabbix-proxy-db: