services:
    zabbix-agent:
        restart: always
        container_name: zabbix-agent
        ports:
            - 10050:10050
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - ZBX_HOSTNAME={$HOSTNAME}
            - ZBX_SERVER_HOST={$SERVER_HOST}
            - ZBX_SERVER_PORT=10051
        privileged: true
        image: zabbix/zabbix-agent2
        deploy:
          resources:
            limits:
              cpus: '1' # Limit CPU Usage to 1 core (optional)
              memory: 100m # Limit Memory Usage to 100 Mib (optional)
        user: root